//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWEBDB_DataAccess.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Core.EntityClient;
    using System.Data.Entity.Infrastructure;
    using System.Data.SqlClient;

    public partial class SWEB_DB_Prm_Entities : DbContext
    {
        public SWEB_DB_Prm_Entities()
            : base(ConnectToSqlServer())
        {
        }
        private static string ConnectToSqlServer()
        {
            SqlConnectionStringBuilder sqlBuilder = new SqlConnectionStringBuilder
            {
                DataSource = "10.45.5.1",
                InitialCatalog = "SWEB_DB",
                PersistSecurityInfo = true,
                IntegratedSecurity = false,
                MultipleActiveResultSets = true,

                UserID = "Administrator",
                Password = "Hey1U9I4am1from0Skidata!",
            };
            var entityConnectionStringBuilder = new EntityConnectionStringBuilder
            {
                Provider = "System.Data.SqlClient",
                ProviderConnectionString = sqlBuilder.ConnectionString,
                Metadata = "res://*/Models.SWEBDB_Prm_Model.csdl|res://*/Models.SWEBDB_Prm_Model.ssdl|res://*/Models.SWEBDB_Prm_Model.msl",
            };

            return entityConnectionStringBuilder.ConnectionString;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TicketValidations> TicketValidations { get; set; }
        public virtual DbSet<ValidationPlans> ValidationPlans { get; set; }
    }
}
